In [40]:
import pandas as pd

In [41]:
df = pd.read_csv('training_set_rel3.tsv', sep='\t', encoding='ISO-8859-1')

#df = pd.read_excel('training_set_rel3.xls')
#df = pd.read_csv('training_set_rel3(full_dataset).tsv', sep='\t', encoding='ISO-8859-1')
df.head()


essay_id  essay_set                                              essay  \
0         1          1  Dear local newspaper, I think effects computer...   
1         2          1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2         3          1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3         4          1  Dear Local Newspaper, @CAPS1 I have found that...   
4         5          1  Dear @LOCATION1, I know having computers has a...   

   rater1_domain1  rater2_domain1  rater3_domain1  domain1_score  \
0             4.0             4.0             NaN            8.0   
1             5.0             4.0             NaN            9.0   
2             4.0             3.0             NaN            7.0   
3             5.0             5.0             NaN           10.0   
4             4.0             4.0             NaN            8.0   

   rater1_domain2  rater2_domain2  domain2_score  ...  rater2_trait3  \
0             NaN             NaN            NaN  ...            NaN   
1             NaN             NaN            NaN  ...            NaN   
2             NaN             NaN            NaN  ...            NaN   
3             NaN             NaN            NaN  ...            NaN   
4             NaN             NaN            NaN  ...            NaN   

   rater2_trait4  rater2_trait5  rater2_trait6  rater3_trait1  rater3_trait2  \
0            NaN            NaN            NaN            NaN            NaN   
1            NaN            NaN            NaN            NaN            NaN   
2            NaN            NaN            NaN            NaN            NaN   
3            NaN            NaN            NaN            NaN            NaN   
4            NaN            NaN            NaN            NaN            NaN   

   rater3_trait3  rater3_trait4  rater3_trait5  rater3_trait6  
0            NaN            NaN            NaN            NaN  
1            NaN            NaN            NaN            NaN  
2            NaN            NaN            NaN            NaN  
3            NaN            NaN            NaN            NaN  
4            NaN            NaN            NaN            NaN  

[5 rows x 28 columns]

In [42]:
df = df.drop(columns=['rater3_domain1', 'rater1_domain2', 'rater2_domain2',
                       'domain2_score', 'rater1_trait1', 'rater1_trait2', 'rater1_trait3',
                        'rater1_trait4', 'rater1_trait5', 'rater1_trait6', 'rater2_trait1',
                       'rater2_trait2', 'rater2_trait3', 'rater2_trait4', 'rater2_trait5',
                       'rater2_trait6', 'rater3_trait1', 'rater3_trait2', 'rater3_trait3',
                        'rater3_trait4', 'rater3_trait5', 'rater3_trait6', 'rater1_domain1', 'rater2_domain1'])
df.columns

Index(['essay_id', 'essay_set', 'essay', 'domain1_score'], dtype='object')

In [43]:
df.head()

essay_id  essay_set                                              essay  \
0         1          1  Dear local newspaper, I think effects computer...   
1         2          1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2         3          1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3         4          1  Dear Local Newspaper, @CAPS1 I have found that...   
4         5          1  Dear @LOCATION1, I know having computers has a...   

   domain1_score  
0            8.0  
1            9.0  
2            7.0  
3           10.0  
4            8.0

In [44]:
df.groupby('domain1_score').describe()

essay_id                                                         \
                 count          mean          std      min       25%      50%   
domain1_score                                                                   
0.0              419.0  10332.035800  2286.169678   5985.0   9312.00   9936.0   
1.0             1736.0   9736.028226  2948.863117   2979.0   7129.75   9519.5   
2.0             2445.0  10349.193456  3606.369687     41.0   7143.00  10093.0   
3.0             2830.0  10060.071731  4784.706422     22.0   4641.25  10476.0   
4.0             1424.0   8540.226826  5449.974753     19.0   3755.75   4574.5   
5.0               96.0   4042.343750  3292.721955     50.0   3194.25   3878.0   
6.0              137.0   3614.197080  6304.502357     14.0    552.00   1041.0   
7.0              163.0   3889.717791  6746.520512      3.0    478.50    966.0   
8.0              737.0   2107.493894  4492.543052      1.0    516.00    963.0   
9.0              383.0   3199.415144  5923.081845      2.0    583.50   1100.0   
10.0             372.0   3567.693548  6421.140345      4.0    496.25   1040.5   
11.0             165.0   6935.260606  8471.107969     24.0    628.00   1349.0   
12.0             133.0  12365.511278  8586.825178     16.0   1170.00  18134.0   
13.0              82.0  18781.024390   528.580372  17836.0  18283.50  18803.5   
14.0             105.0  18723.752381   509.671459  17849.0  18301.00  18700.0   
15.0              86.0  18755.779070   563.725077  17834.0  18211.00  18872.0   
16.0             199.0  18720.020101   513.500081  17841.0  18293.00  18729.0   
17.0             160.0  18676.606250   474.669234  17838.0  18215.50  18759.5   
18.0             118.0  18655.389831   502.406653  17842.0  18235.50  18605.5   
19.0              88.0  18817.068182   494.739472  17846.0  18426.50  18906.5   
20.0             103.0  18787.320388   638.762026  17874.0  18282.50  18725.0   
21.0              70.0  18762.842857   669.944939  17854.0  18228.00  18661.0   
22.0              63.0  18810.444444   601.507991  17906.0  18364.50  18770.0   
23.0              53.0  18706.301887   456.474221  17840.0  18419.00  18657.0   
24.0              99.0  18786.121212   615.376876  17858.0  18362.50  18775.0   
25.0               5.0  21400.200000   216.543760  21031.0  21399.00  21463.0   
26.0               4.0  21117.250000   271.625201  20721.0  21063.00  21208.5   
27.0               6.0  21135.833333   251.920159  20838.0  21021.00  21079.5   
28.0              11.0  21238.909091   254.876619  20828.0  21057.50  21248.0   
29.0               8.0  21029.750000   199.766828  20831.0  20922.50  20937.0   
30.0              49.0  21203.040816   288.925088  20719.0  20925.00  21257.0   
31.0              34.0  21144.558824   273.926023  20727.0  20940.25  21172.0   
32.0              37.0  21162.729730   278.790109  20762.0  20910.00  21103.0   
33.0              32.0  21096.843750   291.619074  20746.0  20799.25  21071.5   
34.0              39.0  21138.358974   252.040357  20716.0  20916.00  21160.0   
35.0              47.0  21225.468085   261.109660  20741.0  21073.50  21192.0   
36.0              65.0  21162.876923   250.214003  20733.0  20968.00  21129.0   
37.0              39.0  21179.871795   232.110135  20779.0  21010.50  21189.0   
38.0              20.0  21175.600000   266.073278  20747.0  20908.25  21237.0   
39.0               8.0  21268.125000   259.060631  20770.0  21161.75  21276.5   
40.0             161.0  21153.006211   262.583308  20718.0  20935.00  21144.0   
41.0              22.0  21236.045455   240.634771  20725.0  21043.75  21328.0   
42.0              23.0  21176.913043   255.081611  20743.0  21007.50  21185.0   
43.0              15.0  21095.266667   218.887273  20734.0  20933.50  21092.0   
44.0              14.0  21158.857143   296.051674  20728.0  20913.50  21118.5   
45.0              31.0  21133.322581   284.789558  20736.0  20844.50  21110.0   
46.0              13.0  21252.384615   236.15

In [45]:
#df = df.dropna()
df['essay'].dropna(inplace=True)

In [46]:
X = df.drop('domain1_score', axis = 1)
len(X['essay'][0])
#print(X['essay'][0])

1875

In [47]:
y = df['domain1_score']

In [48]:
min(df['domain1_score'])

0.0

In [49]:
max(df['domain1_score'])


60.0

In [50]:
df[df['essay_set']==1]['domain1_score']

0        8.0
1        9.0
2        7.0
3       10.0
4        8.0
        ... 
1778     8.0
1779     7.0
1780     8.0
1781     2.0
1782     7.0
Name: domain1_score, Length: 1783, dtype: float64

In [51]:
min_range = [2,1,0,0,0,0,0,0]
max_range = [12,6,3,3,4,4,30,60]

def normalize(x,mi,ma):
    #print("Before Normalization: "+str(x))
    x = (x-mi)/(ma-mi)
    #print("After Normalization : "+str(x))
    return round(x*10)

df['final_score']=df.apply(lambda x:normalize(x['domain1_score'],min_range[x['essay_set']-1],max_range[x['essay_set']-1]),axis=1)

ValueError: cannot convert float NaN to integer

In [13]:
df['final_score']

0       6
1       7
2       5
3       8
4       6
       ..
493     7
494     7
495    10
496     7
497     8
Name: final_score, Length: 498, dtype: int64

In [14]:

df.head()

essay_id  essay_set                                              essay  \
0         1          1  Dear local newspaper, I think effects computer...   
1         2          1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2         3          1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3         4          1  Dear Local Newspaper, @CAPS1 I have found that...   
4         5          1  Dear @LOCATION1, I know having computers has a...   

   domain1_score  final_score  
0              8            6  
1              9            7  
2              7            5  
3             10            8  
4              8            6

In [15]:
df.drop('domain1_score',axis=1,inplace=True)

In [16]:
y = df['final_score']

In [17]:
X.shape

(498, 3)

In [18]:
y.shape

(498,)

In [19]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM, Bidirectional
from tensorflow.keras.layers import Dense

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [20]:
#print(tf.__version__)

In [21]:
voc_size = 10000

In [22]:
import nltk
import re
from nltk.corpus import stopwords

In [23]:
#from nltk.stem.porter import PorterStemmer
#ps = PorterStemmer()
from nltk.stem import WordNetLemmatizer
from collections import defaultdict
from nltk.corpus import wordnet as wn

word_Lemmatized = WordNetLemmatizer()
tag_map = defaultdict(lambda : wn.NOUN)
tag_map['J'] = wn.ADJ
tag_map['V'] = wn.VERB
tag_map['R'] = wn.ADV

essays = X.copy()
corpus = []
for i in range (0, len(essays)):
    #print(i)
    review = re.sub('[^a-zA-Z]', ' ', essays['essay'][i])
    review = review.lower()
    review = review.split()
    
    review = [word_Lemmatized.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

In [24]:
corpus[5]

'dear location think computer negative affect u many people ace camputer daily america num many people go least hour num mean num people cant exercise wasting many posibility physical cap sound good think everything done write letter got got material sit back done writing put material away put letter mailbox walk way back well think write email sitdown move finger see difference cap instead getting good walk friend house talk er know literally computer instead around add anything computer give away information information lead everthing wouldbe gone go online believe phisically get hurt computer long num thing computer cap happened grandpa wood chair day get ardthritis muscle cap thing th'

In [25]:
#onehot_rep = [one_hot(words, voc_size) for words in corpus]
#onehot_rep [0:2]

In [26]:
hparams = {
    "batch_size": 128,
    "cnn_filter_sizes": [128, 128, 128],
    "cnn_kernel_sizes": [5, 5, 5],
    "cnn_pooling_sizes": [5, 5, 40],
    "constraint_learning_rate": 0.01,
    "embedding_dim": 100,
    "embedding_trainable": False,
    "learning_rate": 0.005,
    "max_num_words": 10000,
    "max_sequence_length": 250
}

In [27]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=hparams["max_num_words"])
tokenizer.fit_on_texts(corpus)
text_sequences = tokenizer.texts_to_sequences(corpus)
#text_sequences

In [28]:
sent_length = 1875
embedded_docs = pad_sequences(text_sequences,padding='post',maxlen=hparams["max_sequence_length"])

print(embedded_docs)

[[ 47 113  79 ...   0   0   0]
 [ 47   3   3 ...   0   0   0]
 [ 47   3   3 ...   0   0   0]
 ...
 [127  31 513 ...   2  50 295]
 [ 59   2  12 ...   0   0   0]
 [ 47 113 157 ...   0   0   0]]


In [32]:
from numpy import asarray
embeddings_index = dict()
f = open('glove.6B.200d.txt', encoding="utf8")
for line in f: 
    values = line.split()
    word = values[0]
    coefs = asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


In [33]:
# create a weight matrix for words in training docs
from numpy import zeros
vocab_size = len(tokenizer.word_index) + 1
embedding_matrix = zeros((vocab_size, 200))
for word, i in tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

## Creating the model_1
from tensorflow.keras.layers import Dropout, Conv1D, MaxPooling1D
embedding_vector_features=50
model=Sequential()
e = Embedding(vocab_size, 200, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)
#model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
#model.add(LSTM(100))
#model.add(Dense(1,activation='sigmoid'))
#model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.add(LSTM(100, dropout=0.4, recurrent_dropout=0.2, input_shape=[1, 300], return_sequences=True))
model.add(LSTM(64, recurrent_dropout=0.2))
model.add(Dropout(0.2))
model.add(Dense(1,activation='linear'))
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['mean_squared_error'])
#model.compile(loss='categorical_crossentropy',optimizer='rmsprop', metrics=['categorical_accuracy'])
print(model.summary())

from tensorflow.keras.utils import plot_model
plot_model(model, to_file='model_plot1.png', show_shapes=True, show_layer_names=True)

## Creating the model_2
from tensorflow.keras.layers import Dropout, Conv1D, MaxPooling1D

embedding_vector_features=50

model=Sequential()
e = Embedding(vocab_size, 200, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)

model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))

model.add(LSTM(100, dropout=0.4, recurrent_dropout=0.2, input_shape=[1, 300], return_sequences=True))
model.add(Bidirectional(LSTM(64, recurrent_dropout=0.2)))
model.add(Dropout(0.2))
model.add(Dense(1,activation='linear'))
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['mean_squared_error'])

print(model.summary())

plot_model(model, to_file='model_plot2.png', show_shapes=True, show_layer_names=True)

In [34]:
## Creating the model_3
from tensorflow.keras.layers import Dropout, Conv1D, MaxPooling1D, concatenate, Embedding, GlobalAveragePooling1D
from tensorflow.keras.layers import Input, Flatten
from tensorflow.keras.models import Model

def get_model():
    embedding_vector_features=50
    # define set of input
    deep_inputs = Input(shape=hparams["max_sequence_length"],)

    embedding_layer = Embedding(vocab_size, 200, weights=[embedding_matrix], input_length=4, trainable=False, mask_zero=True)(deep_inputs)

    # the first branch operates on the first input
    x = Conv1D(filters=64, kernel_size=3, padding='same', activation='relu')(embedding_layer)
    x = GlobalAveragePooling1D()(x)

    xx = Conv1D(filters=64, kernel_size=2, padding='same', activation='relu')(embedding_layer)
    xx = GlobalAveragePooling1D()(xx)


    # the second branch opreates on the second input Bidirectional(
    y = Bidirectional(LSTM(50, recurrent_dropout=0.2, return_sequences=False))(embedding_layer)

    # combine the output of the two branches
    combined = concatenate([x,xx,y])
    #combined = concatenate()[x, xx, y]

    # apply a FC layer and then a regression prediction on the combined outputs
    out = Dense(64, activation="relu")(combined)
    #out = tf.keras.layers.BatchNormalization()(out)
    #out = Dropout(0.2)(out)

    out = Dense(32, activation="relu")(out)
    #out = tf.keras.layers.BatchNormalization()(out)
    #out = Dropout(0.2)(out)

    out = Dense(16, activation="relu")(out)

    out = Dense(1, activation="linear")(out)

    # our model will accept the inputs of the two branches and
    # then output a single value
    model = Model(inputs=deep_inputs, outputs=out)
    return model

model = get_model()
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['mean_squared_error'])

print(model.summary())

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 250)]        0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 250, 200)     1325400     input_1[0][0]                    
__________________________________________________________________________________________________
conv1d (Conv1D)                 (None, 250, 64)      38464       embedding[0][0]                  
__________________________________________________________________________________________________
conv1d_1 (Conv1D)               (None, 250, 64)      25664       embedding[0][0]                  
______________________________________________________________________________________________

combined.shape

from tensorflow.keras.utils import plot_model 
plot_model(model, to_file='model_plot4.png', show_shapes=True, show_layer_names=True)

In [45]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [46]:
X_final

array([[ 47, 113,  79, ...,   0,   0,   0],
       [ 47,   3,   3, ...,   0,   0,   0],
       [ 47,   3,   3, ...,   0,   0,   0],
       ...,
       [127,  31, 513, ...,   2,  50, 295],
       [ 59,   2,  12, ...,   0,   0,   0],
       [ 47, 113, 157, ...,   0,   0,   0]])

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)
X_test

array([[  16,    6, 2154, ...,    1,   38,  120],
       [ 101,    1,   23, ...,    0,    0,    0],
       [ 101,  611, 1622, ...,   69,  373,   41],
       ...,
       [   1,   23,    6, ...,    0,    0,    0],
       [  58,    2,  135, ...,    0,    0,    0],
       [  47,    3,    3, ...,    0,    0,    0]])

In [48]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

checkpoint = ModelCheckpoint(filepath = 'checkpoint.h5', verbose = 1, save_best_only = True, save_weights_only = False)
earlyStop = EarlyStopping(monitor = 'val_loss', patience = 3, verbose = 1, mode = 'auto')

callbacksList = [checkpoint, earlyStop]
## Training 
model.fit(X_train, y_train, validation_data=(X_test,y_test),epochs=500,batch_size=64, callbacks = callbacksList)

model.load_weights("checkpoint.h5")

Epoch 1/500
6/6 [==============================] - 17s 1s/step - loss: 37.7178 - mean_squared_error: 37.7178 - val_loss: 24.8665 - val_mean_squared_error: 24.8665

Epoch 00001: val_loss improved from inf to 24.86649, saving model to checkpoint.h5
Epoch 2/500
6/6 [==============================] - 6s 921ms/step - loss: 15.4555 - mean_squared_error: 15.4555 - val_loss: 3.3686 - val_mean_squared_error: 3.3686

Epoch 00002: val_loss improved from 24.86649 to 3.36863, saving model to checkpoint.h5
Epoch 3/500
6/6 [==============================] - 6s 959ms/step - loss: 2.9067 - mean_squared_error: 2.9067 - val_loss: 5.2085 - val_mean_squared_error: 5.2085

Epoch 00003: val_loss did not improve from 3.36863
Epoch 4/500
6/6 [==============================] - 5s 913ms/step - loss: 4.0652 - mean_squared_error: 4.0652 - val_loss: 1.6703 - val_mean_squared_error: 1.6703

Epoch 00004: val_loss improved from 3.36863 to 1.67033, saving model to checkpoint.h5
Epoch 5/500
6/6 [========================

In [49]:
y_test.shape

(165,)

In [50]:
## from tensorflow.keras.layers import Dropout, Conv1D, MaxPooling1D
## Creating model
## embedding_vector_features=40
## model=Sequential()
## model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
## model.add(Dropout(0.3))
## model.add(LSTM(100))
## model.add(Dropout(0.3))
## model.add(Dense(1,activation='sigmoid'))
## model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [51]:
y_pred=model.predict(X_test)
#X_test
from sklearn.metrics import mean_squared_error
print("Mean squared error:%.2f"%mean_squared_error(y_test,y_pred))
print("Root Mean squared error:%.2f"%np.sqrt(mean_squared_error(y_test,y_pred)))

Mean squared error:1.13
Root Mean squared error:1.06


In [52]:
y_test

array([ 6,  5, 10,  8,  7,  9,  6,  8,  6,  7,  7,  6,  6,  6,  6,  6,  5,
        8,  8,  6,  8,  9,  6,  6,  5,  6,  8,  5,  8,  5,  6,  8,  8,  5,
        8,  6,  7,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  6,  8,  6,  9,
        6,  6, 10,  2,  6,  6,  7,  6,  7,  6,  5,  5,  8,  8, 10,  6,  8,
        6,  7,  5,  8,  6, 10,  7,  8,  9,  8,  5,  6,  6,  7,  9,  8,  8,
        3,  8,  6,  7,  7,  6,  8,  6,  8, 10,  7,  8,  4,  8,  7,  7,  6,
        5,  6,  4,  5,  7,  9,  7,  7,  8,  7,  8,  4,  7,  6,  6,  6,  6,
        7, 10, 10,  7,  8,  4,  6,  8,  6,  9,  9,  6,  5,  6,  6,  6,  6,
        6,  6,  5,  8,  6,  5,  9,  5,  5,  8,  6,  6,  6,  6,  6,  5,  8,
        4, 10,  6,  9,  7,  8,  6,  8,  6,  2,  8,  6], dtype=int64)

In [53]:
y_pred

array([[8.148088 ],
       [6.617607 ],
       [7.986351 ],
       [6.741458 ],
       [6.0841274],
       [8.194379 ],
       [5.9210715],
       [7.87213  ],
       [7.0481896],
       [7.283901 ],
       [8.627767 ],
       [5.576251 ],
       [5.88008  ],
       [6.9556103],
       [5.8780403],
       [7.0311747],
       [6.8986835],
       [8.386816 ],
       [5.9591403],
       [6.646431 ],
       [8.680591 ],
       [8.165513 ],
       [6.098136 ],
       [7.2813897],
       [4.8956456],
       [6.197837 ],
       [8.172848 ],
       [5.3252077],
       [7.870454 ],
       [5.2678113],
       [7.1674943],
       [8.426665 ],
       [8.305725 ],
       [6.2113605],
       [5.799363 ],
       [7.2116375],
       [6.9682064],
       [7.1509957],
       [5.9049788],
       [5.922588 ],
       [6.701441 ],
       [6.7894697],
       [6.57765  ],
       [6.9491186],
       [5.9374156],
       [6.6122484],
       [6.0305386],
       [5.5909777],
       [7.692382 ],
       [5.554374 ],


In [54]:
#from sklearn.metrics import confusion_matrix
#confusion_matrix(y_test,y_pred)

In [55]:
#from sklearn.metrics import accuracy_score
#accuracy_score(y_test,y_pred)

In [56]:
from sklearn.metrics import cohen_kappa_score
y_pred = np.around(y_pred)
result = cohen_kappa_score(y_test,y_pred,weights='quadratic')
print("Kappa Score: {}".format(result))

Kappa Score: 0.6688311688311688
